/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bakdata.profilestore.recommender.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AdjacencyList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4387811912214649660L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdjacencyList\",\"namespace\":\"com.bakdata.profilestore.recommender.avro\",\"fields\":[{\"name\":\"neighbors\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AdjacencyList> ENCODER =
      new BinaryMessageEncoder<AdjacencyList>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AdjacencyList> DECODER =
      new BinaryMessageDecoder<AdjacencyList>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AdjacencyList> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AdjacencyList> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AdjacencyList> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AdjacencyList>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AdjacencyList to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AdjacencyList from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AdjacencyList instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AdjacencyList fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<java.lang.Long> neighbors;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AdjacencyList() {}

  /**
   * All-args constructor.
   * @param neighbors The new value for neighbors
   */
  public AdjacencyList(java.util.List<java.lang.Long> neighbors) {
    this.neighbors = neighbors;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return neighbors;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: neighbors = (java.util.List<java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'neighbors' field.
   * @return The value of the 'neighbors' field.
   */
  public java.util.List<java.lang.Long> getNeighbors() {
    return neighbors;
  }


  /**
   * Sets the value of the 'neighbors' field.
   * @param value the value to set.
   */
  public void setNeighbors(java.util.List<java.lang.Long> value) {
    this.neighbors = value;
  }

  /**
   * Creates a new AdjacencyList RecordBuilder.
   * @return A new AdjacencyList RecordBuilder
   */
  public static com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder newBuilder() {
    return new com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder();
  }

  /**
   * Creates a new AdjacencyList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AdjacencyList RecordBuilder
   */
  public static com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder newBuilder(com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder other) {
    if (other == null) {
      return new com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder();
    } else {
      return new com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder(other);
    }
  }

  /**
   * Creates a new AdjacencyList RecordBuilder by copying an existing AdjacencyList instance.
   * @param other The existing instance to copy.
   * @return A new AdjacencyList RecordBuilder
   */
  public static com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder newBuilder(com.bakdata.profilestore.recommender.avro.AdjacencyList other) {
    if (other == null) {
      return new com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder();
    } else {
      return new com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder(other);
    }
  }

  /**
   * RecordBuilder for AdjacencyList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdjacencyList>
    implements org.apache.avro.data.RecordBuilder<AdjacencyList> {

    private java.util.List<java.lang.Long> neighbors;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.neighbors)) {
        this.neighbors = data().deepCopy(fields()[0].schema(), other.neighbors);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AdjacencyList instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bakdata.profilestore.recommender.avro.AdjacencyList other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.neighbors)) {
        this.neighbors = data().deepCopy(fields()[0].schema(), other.neighbors);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'neighbors' field.
      * @return The value.
      */
    public java.util.List<java.lang.Long> getNeighbors() {
      return neighbors;
    }


    /**
      * Sets the value of the 'neighbors' field.
      * @param value The value of 'neighbors'.
      * @return This builder.
      */
    public com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder setNeighbors(java.util.List<java.lang.Long> value) {
      validate(fields()[0], value);
      this.neighbors = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'neighbors' field has been set.
      * @return True if the 'neighbors' field has been set, false otherwise.
      */
    public boolean hasNeighbors() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'neighbors' field.
      * @return This builder.
      */
    public com.bakdata.profilestore.recommender.avro.AdjacencyList.Builder clearNeighbors() {
      neighbors = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AdjacencyList build() {
      try {
        AdjacencyList record = new AdjacencyList();
        record.neighbors = fieldSetFlags()[0] ? this.neighbors : (java.util.List<java.lang.Long>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AdjacencyList>
    WRITER$ = (org.apache.avro.io.DatumWriter<AdjacencyList>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AdjacencyList>
    READER$ = (org.apache.avro.io.DatumReader<AdjacencyList>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.neighbors.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.Long e0: this.neighbors) {
      actualSize0++;
      out.startItem();
      out.writeLong(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<java.lang.Long> a0 = this.neighbors;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("neighbors").schema());
        this.neighbors = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readLong();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.Long> a0 = this.neighbors;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("neighbors").schema());
            this.neighbors = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readLong();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










