/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bakdata.profilestore.core.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ChartTuple extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6584097129484189281L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChartTuple\",\"namespace\":\"com.bakdata.profilestore.core.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"countPlays\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ChartTuple> ENCODER =
      new BinaryMessageEncoder<ChartTuple>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ChartTuple> DECODER =
      new BinaryMessageDecoder<ChartTuple>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ChartTuple> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ChartTuple> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ChartTuple> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ChartTuple>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ChartTuple to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ChartTuple from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ChartTuple instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ChartTuple fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public long countPlays;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ChartTuple() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param countPlays The new value for countPlays
   */
  public ChartTuple(java.lang.Long id, java.lang.Long countPlays) {
    this.id = id;
    this.countPlays = countPlays;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return countPlays;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: countPlays = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'countPlays' field.
   * @return The value of the 'countPlays' field.
   */
  public long getCountPlays() {
    return countPlays;
  }


  /**
   * Sets the value of the 'countPlays' field.
   * @param value the value to set.
   */
  public void setCountPlays(long value) {
    this.countPlays = value;
  }

  /**
   * Creates a new ChartTuple RecordBuilder.
   * @return A new ChartTuple RecordBuilder
   */
  public static com.bakdata.profilestore.core.avro.ChartTuple.Builder newBuilder() {
    return new com.bakdata.profilestore.core.avro.ChartTuple.Builder();
  }

  /**
   * Creates a new ChartTuple RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ChartTuple RecordBuilder
   */
  public static com.bakdata.profilestore.core.avro.ChartTuple.Builder newBuilder(com.bakdata.profilestore.core.avro.ChartTuple.Builder other) {
    if (other == null) {
      return new com.bakdata.profilestore.core.avro.ChartTuple.Builder();
    } else {
      return new com.bakdata.profilestore.core.avro.ChartTuple.Builder(other);
    }
  }

  /**
   * Creates a new ChartTuple RecordBuilder by copying an existing ChartTuple instance.
   * @param other The existing instance to copy.
   * @return A new ChartTuple RecordBuilder
   */
  public static com.bakdata.profilestore.core.avro.ChartTuple.Builder newBuilder(com.bakdata.profilestore.core.avro.ChartTuple other) {
    if (other == null) {
      return new com.bakdata.profilestore.core.avro.ChartTuple.Builder();
    } else {
      return new com.bakdata.profilestore.core.avro.ChartTuple.Builder(other);
    }
  }

  /**
   * RecordBuilder for ChartTuple instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChartTuple>
    implements org.apache.avro.data.RecordBuilder<ChartTuple> {

    private long id;
    private long countPlays;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bakdata.profilestore.core.avro.ChartTuple.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.countPlays)) {
        this.countPlays = data().deepCopy(fields()[1].schema(), other.countPlays);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ChartTuple instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bakdata.profilestore.core.avro.ChartTuple other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.countPlays)) {
        this.countPlays = data().deepCopy(fields()[1].schema(), other.countPlays);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.ChartTuple.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.ChartTuple.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'countPlays' field.
      * @return The value.
      */
    public long getCountPlays() {
      return countPlays;
    }


    /**
      * Sets the value of the 'countPlays' field.
      * @param value The value of 'countPlays'.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.ChartTuple.Builder setCountPlays(long value) {
      validate(fields()[1], value);
      this.countPlays = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'countPlays' field has been set.
      * @return True if the 'countPlays' field has been set, false otherwise.
      */
    public boolean hasCountPlays() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'countPlays' field.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.ChartTuple.Builder clearCountPlays() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ChartTuple build() {
      try {
        ChartTuple record = new ChartTuple();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.countPlays = fieldSetFlags()[1] ? this.countPlays : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ChartTuple>
    WRITER$ = (org.apache.avro.io.DatumWriter<ChartTuple>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ChartTuple>
    READER$ = (org.apache.avro.io.DatumReader<ChartTuple>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeLong(this.countPlays);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.countPlays = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.countPlays = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










