/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bakdata.profilestore.core.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CompositeKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -88124941488875489L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CompositeKey\",\"namespace\":\"com.bakdata.profilestore.core.avro\",\"fields\":[{\"name\":\"primaryKey\",\"type\":\"long\"},{\"name\":\"secondaryKey\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CompositeKey> ENCODER =
      new BinaryMessageEncoder<CompositeKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CompositeKey> DECODER =
      new BinaryMessageDecoder<CompositeKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CompositeKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CompositeKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CompositeKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CompositeKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CompositeKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CompositeKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CompositeKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CompositeKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long primaryKey;
  @Deprecated public long secondaryKey;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CompositeKey() {}

  /**
   * All-args constructor.
   * @param primaryKey The new value for primaryKey
   * @param secondaryKey The new value for secondaryKey
   */
  public CompositeKey(java.lang.Long primaryKey, java.lang.Long secondaryKey) {
    this.primaryKey = primaryKey;
    this.secondaryKey = secondaryKey;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return primaryKey;
    case 1: return secondaryKey;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: primaryKey = (java.lang.Long)value$; break;
    case 1: secondaryKey = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'primaryKey' field.
   * @return The value of the 'primaryKey' field.
   */
  public long getPrimaryKey() {
    return primaryKey;
  }


  /**
   * Sets the value of the 'primaryKey' field.
   * @param value the value to set.
   */
  public void setPrimaryKey(long value) {
    this.primaryKey = value;
  }

  /**
   * Gets the value of the 'secondaryKey' field.
   * @return The value of the 'secondaryKey' field.
   */
  public long getSecondaryKey() {
    return secondaryKey;
  }


  /**
   * Sets the value of the 'secondaryKey' field.
   * @param value the value to set.
   */
  public void setSecondaryKey(long value) {
    this.secondaryKey = value;
  }

  /**
   * Creates a new CompositeKey RecordBuilder.
   * @return A new CompositeKey RecordBuilder
   */
  public static com.bakdata.profilestore.core.avro.CompositeKey.Builder newBuilder() {
    return new com.bakdata.profilestore.core.avro.CompositeKey.Builder();
  }

  /**
   * Creates a new CompositeKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CompositeKey RecordBuilder
   */
  public static com.bakdata.profilestore.core.avro.CompositeKey.Builder newBuilder(com.bakdata.profilestore.core.avro.CompositeKey.Builder other) {
    if (other == null) {
      return new com.bakdata.profilestore.core.avro.CompositeKey.Builder();
    } else {
      return new com.bakdata.profilestore.core.avro.CompositeKey.Builder(other);
    }
  }

  /**
   * Creates a new CompositeKey RecordBuilder by copying an existing CompositeKey instance.
   * @param other The existing instance to copy.
   * @return A new CompositeKey RecordBuilder
   */
  public static com.bakdata.profilestore.core.avro.CompositeKey.Builder newBuilder(com.bakdata.profilestore.core.avro.CompositeKey other) {
    if (other == null) {
      return new com.bakdata.profilestore.core.avro.CompositeKey.Builder();
    } else {
      return new com.bakdata.profilestore.core.avro.CompositeKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for CompositeKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CompositeKey>
    implements org.apache.avro.data.RecordBuilder<CompositeKey> {

    private long primaryKey;
    private long secondaryKey;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bakdata.profilestore.core.avro.CompositeKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.primaryKey)) {
        this.primaryKey = data().deepCopy(fields()[0].schema(), other.primaryKey);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.secondaryKey)) {
        this.secondaryKey = data().deepCopy(fields()[1].schema(), other.secondaryKey);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CompositeKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bakdata.profilestore.core.avro.CompositeKey other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.primaryKey)) {
        this.primaryKey = data().deepCopy(fields()[0].schema(), other.primaryKey);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.secondaryKey)) {
        this.secondaryKey = data().deepCopy(fields()[1].schema(), other.secondaryKey);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'primaryKey' field.
      * @return The value.
      */
    public long getPrimaryKey() {
      return primaryKey;
    }


    /**
      * Sets the value of the 'primaryKey' field.
      * @param value The value of 'primaryKey'.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.CompositeKey.Builder setPrimaryKey(long value) {
      validate(fields()[0], value);
      this.primaryKey = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'primaryKey' field has been set.
      * @return True if the 'primaryKey' field has been set, false otherwise.
      */
    public boolean hasPrimaryKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'primaryKey' field.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.CompositeKey.Builder clearPrimaryKey() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'secondaryKey' field.
      * @return The value.
      */
    public long getSecondaryKey() {
      return secondaryKey;
    }


    /**
      * Sets the value of the 'secondaryKey' field.
      * @param value The value of 'secondaryKey'.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.CompositeKey.Builder setSecondaryKey(long value) {
      validate(fields()[1], value);
      this.secondaryKey = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'secondaryKey' field has been set.
      * @return True if the 'secondaryKey' field has been set, false otherwise.
      */
    public boolean hasSecondaryKey() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'secondaryKey' field.
      * @return This builder.
      */
    public com.bakdata.profilestore.core.avro.CompositeKey.Builder clearSecondaryKey() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CompositeKey build() {
      try {
        CompositeKey record = new CompositeKey();
        record.primaryKey = fieldSetFlags()[0] ? this.primaryKey : (java.lang.Long) defaultValue(fields()[0]);
        record.secondaryKey = fieldSetFlags()[1] ? this.secondaryKey : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CompositeKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<CompositeKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CompositeKey>
    READER$ = (org.apache.avro.io.DatumReader<CompositeKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.primaryKey);

    out.writeLong(this.secondaryKey);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.primaryKey = in.readLong();

      this.secondaryKey = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.primaryKey = in.readLong();
          break;

        case 1:
          this.secondaryKey = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










